2014-02-25 22:32:07,916 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractSavePersistentMethod.doInvokeInternal(AbstractSavePersistentMethod.java:190)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractDynamicPersistentMethod.invoke(AbstractDynamicPersistentMethod.java:63)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormInstanceApi.save(HibernateGormInstanceApi.groovy:195)
	at mycity.LocalArea.save(LocalArea.groovy)
	at mycity.LocalArea$save.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1254)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1086)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:960)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:405)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:75)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:109)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4961)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5455)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:32:07,918 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:32:07,918 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:32:07,919 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:32:07,919 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:32:07,919 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:33:39,634 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.dao.DataIntegrityViolationException: could not insert: [mycity.LocalArea]; SQL [insert into local_area (id, version, name, polygon) values (null, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:648)
	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:411)
	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:339)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.SavePersistentMethod.performSave(SavePersistentMethod.java:56)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractSavePersistentMethod.doInvokeInternal(AbstractSavePersistentMethod.java:215)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractDynamicPersistentMethod.invoke(AbstractDynamicPersistentMethod.java:63)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormInstanceApi.save(HibernateGormInstanceApi.groovy:195)
	at mycity.LocalArea.save(LocalArea.groovy)
	at mycity.LocalArea$save.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1254)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1086)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:960)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:405)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:75)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:109)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4961)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5455)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:102)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:63)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2346)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2853)
	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:71)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:273)
	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventTriggeringInterceptor.performSaveOrReplicate(ClosureEventTriggeringInterceptor.java:246)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:203)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:129)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:210)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:195)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:117)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:93)
	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventTriggeringInterceptor.onSaveOrUpdate(ClosureEventTriggeringInterceptor.java:104)
	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:685)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:677)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:673)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.SavePersistentMethod$1.doInHibernate(SavePersistentMethod.java:58)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:406)
	... 43 more
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:93)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:56)
	... 60 more
2014-02-25 22:33:39,635 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:102)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:63)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2346)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2853)
	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:71)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:273)
	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventTriggeringInterceptor.performSaveOrReplicate(ClosureEventTriggeringInterceptor.java:246)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:203)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:129)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:210)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:195)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:117)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:93)
	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventTriggeringInterceptor.onSaveOrUpdate(ClosureEventTriggeringInterceptor.java:104)
	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:685)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:677)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:673)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.SavePersistentMethod$1.doInHibernate(SavePersistentMethod.java:58)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:406)
	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:339)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.SavePersistentMethod.performSave(SavePersistentMethod.java:56)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractSavePersistentMethod.doInvokeInternal(AbstractSavePersistentMethod.java:215)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractDynamicPersistentMethod.invoke(AbstractDynamicPersistentMethod.java:63)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormInstanceApi.save(HibernateGormInstanceApi.groovy:195)
	at mycity.LocalArea.save(LocalArea.groovy)
	at mycity.LocalArea$save.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1254)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1086)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:960)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:405)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:75)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:109)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4961)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5455)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:93)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:56)
	... 60 more
2014-02-25 22:33:39,636 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:93)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:56)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2346)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2853)
	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:71)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:273)
	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventTriggeringInterceptor.performSaveOrReplicate(ClosureEventTriggeringInterceptor.java:246)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:203)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:129)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:210)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:195)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:117)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:93)
	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventTriggeringInterceptor.onSaveOrUpdate(ClosureEventTriggeringInterceptor.java:104)
	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:685)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:677)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:673)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.SavePersistentMethod$1.doInHibernate(SavePersistentMethod.java:58)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:406)
	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:339)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.SavePersistentMethod.performSave(SavePersistentMethod.java:56)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractSavePersistentMethod.doInvokeInternal(AbstractSavePersistentMethod.java:215)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractDynamicPersistentMethod.invoke(AbstractDynamicPersistentMethod.java:63)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormInstanceApi.save(HibernateGormInstanceApi.groovy:195)
	at mycity.LocalArea.save(LocalArea.groovy)
	at mycity.LocalArea$save.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1254)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1086)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:960)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:405)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:75)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:109)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4961)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5455)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:33:39,636 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.dao.DataIntegrityViolationException: could not insert: [mycity.LocalArea]; SQL [insert into local_area (id, version, name, polygon) values (null, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	... 9 more
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	... 9 more
2014-02-25 22:33:39,636 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.dao.DataIntegrityViolationException: could not insert: [mycity.LocalArea]; SQL [insert into local_area (id, version, name, polygon) values (null, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	... 9 more
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	... 9 more
2014-02-25 22:33:39,636 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	... 9 more
2014-02-25 22:33:39,636 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:33:39,637 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.dao.DataIntegrityViolationException: could not insert: [mycity.LocalArea]; SQL [insert into local_area (id, version, name, polygon) values (null, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	... 9 more
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	... 9 more
2014-02-25 22:33:39,637 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.dao.DataIntegrityViolationException: could not insert: [mycity.LocalArea]; SQL [insert into local_area (id, version, name, polygon) values (null, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	... 9 more
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	... 9 more
2014-02-25 22:33:39,637 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	... 9 more
2014-02-25 22:33:39,637 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:33:39,637 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.springframework.dao.DataIntegrityViolationException: could not insert: [mycity.LocalArea]; SQL [insert into local_area (id, version, name, polygon) values (null, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.hibernate.exception.DataException: could not insert: [mycity.LocalArea]
	... 9 more
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "POLYGON VARCHAR(255) NOT NULL": "'-123.16407742426055,49.257482642589025 -123.16385512340415,49.257459575262544 -123.16363263565299,49.257448468979263 -123.16264... (8754)"; SQL statement:
insert into local_area (id, version, name, polygon) values (null, ?, ?, ?) [22001-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:317)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:699)
	at org.h2.command.dml.Insert.insertRows(Insert.java:123)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	... 9 more
2014-02-25 22:36:25,779 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
groovy.lang.MissingPropertyException: No such property: ”12345” for class: BootStrap
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:50)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:231)
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1254)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1086)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:960)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:405)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:75)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:109)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4961)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5455)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:36:25,790 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
groovy.lang.MissingPropertyException: No such property: ”12345” for class: BootStrap
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:36:25,790 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
groovy.lang.MissingPropertyException: No such property: ”12345” for class: BootStrap
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:36:25,791 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
groovy.lang.MissingPropertyException: No such property: ”12345” for class: BootStrap
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:36:25,791 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
groovy.lang.MissingPropertyException: No such property: ”12345” for class: BootStrap
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:36:25,792 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
groovy.lang.MissingPropertyException: No such property: ”12345” for class: BootStrap
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:39:42,082 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractSavePersistentMethod.doInvokeInternal(AbstractSavePersistentMethod.java:190)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractDynamicPersistentMethod.invoke(AbstractDynamicPersistentMethod.java:63)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormInstanceApi.save(HibernateGormInstanceApi.groovy:195)
	at mycity.LocalArea.save(LocalArea.groovy)
	at mycity.LocalArea$save.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1254)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1086)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:960)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:405)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:75)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:109)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4961)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5455)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:39:42,083 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:39:42,084 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:39:42,084 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:39:42,084 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-25 22:39:42,084 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'mycity.LocalArea' on field 'polygon': rejected value [null]; codes [mycity.LocalArea.polygon.nullable.error.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.error.polygon,mycity.LocalArea.polygon.nullable.error.java.lang.String,mycity.LocalArea.polygon.nullable.error,localArea.polygon.nullable.error.mycity.LocalArea.polygon,localArea.polygon.nullable.error.polygon,localArea.polygon.nullable.error.java.lang.String,localArea.polygon.nullable.error,mycity.LocalArea.polygon.nullable.mycity.LocalArea.polygon,mycity.LocalArea.polygon.nullable.polygon,mycity.LocalArea.polygon.nullable.java.lang.String,mycity.LocalArea.polygon.nullable,localArea.polygon.nullable.mycity.LocalArea.polygon,localArea.polygon.nullable.polygon,localArea.polygon.nullable.java.lang.String,localArea.polygon.nullable,nullable.mycity.LocalArea.polygon,nullable.polygon,nullable.java.lang.String,nullable]; arguments [polygon,class mycity.LocalArea]; default message [Property [{0}] of class [{1}] cannot be null]

	at BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
